### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/shotty#1]
- [ ] Post-screenshot actions
  - [ ] Automatic quit
  - [ ] Upload to imgur
- [ ] Options
  - [ ] Default save path
  - [ ] Delay
- [ ] Proper menu button instead of menubar
- [ ] Updater / uninstaller
